# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, upload_to='photos')),
                ('bio', models.TextField(blank=True)),
                ('joined_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
