# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(max_length=250)),
                ('status', models.CharField(default='To Do', max_length=250)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User')),
            ],
        ),
    ]
