# Generated by Django 2.2 on 2019-04-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='percent_complete',
            field=models.IntegerField(default=0),
        ),
    ]
