# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Bug', 'Bug Report'), ('Feature', 'Feature Request')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
